### ISSUE TITLE
GET /sports-place-types responds with status 500

### ISSUE THREAD

**Issue by lauri-n** [lipas-liikuntapaikat/lipas-api#2]
Currently calling the GET /sports-place-types method in API responds with HTTP 500.
This was still working fine just recently.

```
HTTP ERROR 500 java.lang.NullPointerException: Response map is nil
URI:	/api/sports-place-types
STATUS:	500
MESSAGE:	java.lang.NullPointerException: Response map is nil
SERVLET:	-
CAUSED BY:	java.lang.NullPointerException: Response map is nil
Caused by:

java.lang.NullPointerException: Response map is nil
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:102)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:93)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:97)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:93)
	at ring.adapter.jetty$proxy_handler$fn__427.invoke(jetty.clj:28)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by veeveel** [comment]
Seconded, same with http://lipas.cc.jyu.fi/api/categories

**Comment by vharmain** [comment]
This is a bug related to a recent server-transition. I will fix tonight/tomorrow and will provide an update here. Thanks for reporting!

**Comment by vharmain** [comment]
Also sorry for the long delay. I had bad notification settings for this repo. 🙈 Normally we react quickly to bugs.

**Comment by vharmain** [comment]
These are now fixed. The problem was a missing context path in the new server environment. Could you @veeveel and @lauri-n please verify and then I'll close this issue.

**Comment by lauri-n** [comment]
Both sports-place-types and categories work again, thanks.

**Comment by veeveel** [comment]
Everything works as before, thanks!
